In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('산일구비_데이터셋.xlsx', sheet_name = 'Sheet1')
df

       구     동
0    종로구   사직동
1    종로구   삼청동
2    종로구   부암동
3    종로구   평창동
4    종로구   무악동
..   ...   ...
421  강동구  천호2동
422  강동구    길동
423  강동구   강일동
424  강동구  상일1동
425  강동구  상일2동

[426 rows x 2 columns]

In [3]:
d = []
for i in df['동'] :
    d.append(i)
d[8]='종로5.6가동'
d

['사직동',
 '삼청동',
 '부암동',
 '평창동',
 '무악동',
 '교남동',
 '가회동',
 '종로1.2.3.4가동',
 '종로5.6가동',
 '이화동',
 '창신1동',
 '창신2동',
 '창신3동',
 '숭인1동',
 '숭인2동',
 '청운효자동',
 '혜화동',
 '소공동',
 '회현동',
 '명동',
 '필동',
 '장충동',
 '광희동',
 '을지로동',
 '신당5동',
 '황학동',
 '중림동',
 '신당동',
 '다산동',
 '약수동',
 '청구동',
 '동화동',
 '후암동',
 '용산2가동',
 '남영동',
 '원효로2동',
 '효창동',
 '용문동',
 '이촌1동',
 '이촌2동',
 '이태원1동',
 '이태원2동',
 '서빙고동',
 '보광동',
 '청파동',
 '원효로1동',
 '한강로동',
 '한남동',
 '왕십리2동',
 '마장동',
 '사근동',
 '행당1동',
 '행당2동',
 '응봉동',
 '금호1가동',
 '금호4가동',
 '성수1가1동',
 '성수1가2동',
 '성수2가1동',
 '성수2가3동',
 '송정동',
 '용답동',
 '왕십리도선동',
 '금호2.3가동',
 '옥수동',
 '화양동',
 '군자동',
 '중곡1동',
 '중곡2동',
 '중곡3동',
 '중곡4동',
 '능동',
 '구의1동',
 '구의2동',
 '구의3동',
 '광장동',
 '자양1동',
 '자양2동',
 '자양3동',
 '자양4동',
 '회기동',
 '휘경1동',
 '휘경2동',
 '청량리동',
 '용신동',
 '제기동',
 '전농1동',
 '전농2동',
 '답십리2동',
 '장안1동',
 '장안2동',
 '이문1동',
 '이문2동',
 '답십리1동',
 '면목2동',
 '면목4동',
 '면목5동',
 '면목7동',
 '상봉1동',
 '상봉2동',
 '중화1동',
 '중화2동',
 '묵1동',
 '묵2동',
 '망우3동',
 '신내1동',
 '신내2동',
 '면목본동',
 '면목3.8동',
 '망우본동',
 '돈암1동',
 '돈암2동',
 '안암동',
 '보문동',
 '정릉1동',
 '정릉2동',
 '정릉3동',
 '정릉4동',
 '길음1동',
 '길음2동',
 '월곡1동',
 '월곡2동',
 '장위1동',
 '장위2동',
 '장위3동',
 '성북동',
 '삼선동',
 '동선동',
 '종암동',
 '석관동',
 '번1동',
 '번2동',
 '번3동',
 '수유1동',
 '수유2동',
 '수유3동',
 '삼양동',
 '미아동',
 '송중동',
 '송천동',
 '삼각산동',
 '우이동',
 '인수동',
 '쌍문1동',
 '쌍문2동',
 '쌍문3동',
 '쌍문4동',
 '방학1동',
 '방학2동',
 '방학3동',
 '창1동',
 '창2동',
 '창3동',
 '창4동',
 '창5동',
 '도봉1동',
 '도봉2동',
 '월계1동',
 '월계2동',
 '월계3동',
 '공릉2동',
 '하계1동',
 '하계2동',
 '중계본동',
 '중계1동',
 '중계4동',
 '상계1동',
 '상계2동',
 '상계5동',
 '상계8동',
 '상계9동',
 '상계10동',
 '상계3.4동',
 '상계6.7동',
 '중계2.3동',
 '공릉1동',
 '녹번동',
 '불광1동',
 '갈현1동',
 '갈현2동',
 '구산동',
 '대조동',
 '응암1동',
 '응암2동',
 '신사1동',
 '신사2동',
 '증산동',
 '수색동',
 '진관동',
 '불광2동',
 '응암3동',
 '역촌동',
 '천연동',
 '홍제1동',
 '홍제3동',
 '홍제2동',
 '홍은1동',
 '홍은2동',
 '남가좌1동',
 '남가좌2동',
 '북가좌1동',
 '북가좌2동',
 '충현동',
 '북아현동',
 '신촌동',
 '연희동',
 '용강동',
 '대흥동',
 '염리동',
 '신수동',
 '서교동',
 '합정동',
 '망원1동',
 '망원2동',
 '연남동',
 '성산1동',
 '성산2동',
 '상암동',
 '도화동',
 '서강동',
 '공덕동',
 '아현동',
 '목1동',
 '목2동',
 '목3동',
 '목4동',
 '신월1동',
 '신월2동',
 '신월3동',
 '신월4동',
 '신월5동',
 '신월6동',
 '신월7동',
 '신정1동',
 '신정2동',
 '신정3동',
 '신정6동',
 '신정7동',
 '목5동',
 '신정4동',
 '염창동',
 '등촌1동',
 '등촌2동',
 '등촌3동',
 '화곡본동',
 '화곡2동',
 '화곡3동',
 '화곡4동',
 '화곡6동',
 '화곡8동',
 '가양1동',
 '가양2동',
 '가양3동',
 '발산1동',
 '공항동',
 '방화1동',
 '방화2동',
 '방화3동',
 '화곡1동',
 '우장산동',
 '신도림동',
 '구로1동',
 '구로3동',
 '구로4동',
 '구로5동',
 '고척1동',
 '고척2동',
 '개봉2동',
 '개봉3동',
 '오류1동',
 '수궁동',
 '가리봉동',
 '구로2동',
 '개봉1동',
 '오류2동',
 '항동',
 '가산동',
 '독산1동',
 '독산2동',
 '독산3동',
 '독산4동',
 '시흥1동',
 '시흥2동',
 '시흥3동',
 '시흥4동',
 '시흥5동',
 '여의동',
 '당산1동',
 '당산2동',
 '양평1동',
 '양평2동',
 '신길1동',
 '신길3동',
 '신길4동',
 '신길5동',
 '신길6동',
 '신길7동',
 '대림1동',
 '대림2동',
 '대림3동',
 '영등포본동',
 '영등포동',
 '도림동',
 '문래동',
 '노량진2동',
 '상도1동',
 '상도2동',
 '상도3동',
 '상도4동',
 '사당1동',
 '사당3동',
 '사당4동',
 '사당5동',
 '대방동',
 '신대방1동',
 '신대방2동',
 '흑석동',
 '노량진1동',
 '사당2동',
 '보라매동',
 '청림동',
 '행운동',
 '낙성대동',
 '중앙동',
 '인헌동',
 '남현동',
 '서원동',
 '신원동',
 '서림동',
 '신사동관',
 '신림동',
 '난향동',
 '조원동',
 '대학동',
 '은천동',
 '성현동',
 '청룡동',
 '난곡동',
 '삼성동',
 '미성동',
 '서초1동',
 '서초2동',
 '서초3동',
 '서초4동',
 '잠원동',
 '반포본동',
 '반포1동',
 '반포2동',
 '반포3동',
 '반포4동',
 '방배본동',
 '방배1동',
 '방배2동',
 '방배3동',
 '방배4동',
 '양재1동',
 '양재2동',
 '내곡동',
 '신사동강',
 '논현1동',
 '논현2동',
 '삼성1동',
 '삼성2동',
 '대치1동',
 '대치4동',
 '역삼1동',
 '역삼2동',
 '도곡1동',
 '도곡2동',
 '개포1동',
 '개포4동',
 '일원본동',
 '일원1동',
 '일원2동',
 '수서동',
 '세곡동',
 '압구정동',
 '청담동',
 '대치2동',
 '개포2동',
 '풍납1동',
 '풍납2동',
 '거여1동',
 '거여2동',
 '마천1동',
 '마천2동',
 '방이1동',
 '방이2동',
 '오륜동',
 '오금동',
 '송파1동',
 '송파2동',
 '석촌동',
 '삼전동',
 '가락본동',
 '가락1동',
 '가락2동',
 '문정1동',
 '문정2동',
 '잠실본동',
 '잠실4동',
 '잠실6동',
 '잠실7동',
 '잠실2동',
 '잠실3동',
 '장지동',
 '위례동',
 '명일1동',
 '명일2동',
 '고덕1동',
 '고덕2동',
 '암사2동',
 '암사3동',
 '천호1동',
 '천호3동',
 '성내1동',
 '성내2동',
 '성내3동',
 '둔촌1동',
 '둔촌2동',
 '암사1동',
 '천호2동',
 '길동',
 '강일동',
 '상일1동',
 '상일2동']

In [4]:
df1 = pd.read_excel('편의점 수.xlsx', sheet_name = 'Sheet1')
df1

      행정구역  전체 점포수
0    청운효자동    13.0
1      NaN     NaN
2      사직동    30.0
3      NaN     NaN
4      삼청동     7.0
..     ...     ...
843    NaN     NaN
844   둔촌1동     4.0
845    NaN     NaN
846   둔촌2동    20.0
847    NaN     NaN

[848 rows x 2 columns]

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848 entries, 0 to 847
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역    424 non-null    object
 1   전체 점포수  424 non-null    float64
dtypes: float64(1), object(1)
memory usage: 13.4+ KB

In [6]:
df1.isna().sum()

행정구역      424
전체 점포수    424
dtype: int64

In [7]:
df1 = df1.dropna()
df1

      행정구역  전체 점포수
0    청운효자동    13.0
2      사직동    30.0
4      삼청동     7.0
6      부암동    10.0
8      평창동    15.0
..     ...     ...
838   성내2동    30.0
840   성내3동    33.0
842     길동    60.0
844   둔촌1동     4.0
846   둔촌2동    20.0

[424 rows x 2 columns]

In [8]:
df1.reset_index(drop=True, inplace=True)
df1

      행정구역  전체 점포수
0    청운효자동    13.0
1      사직동    30.0
2      삼청동     7.0
3      부암동    10.0
4      평창동    15.0
..     ...     ...
419   성내2동    30.0
420   성내3동    33.0
421     길동    60.0
422   둔촌1동     4.0
423   둔촌2동    20.0

[424 rows x 2 columns]

In [9]:
dong = []
num = []
for i in df1['행정구역'] :
    dong.append(i)
for j in df1['전체 점포수'] :
    num.append(j)

In [10]:
# 데이터셋에는 있지만 편의점에는 없는 것
for i in d :
    if i not in dong :
        print(i)

항동
상일1동
상일2동

In [11]:
# 편의점에는 있지만 데이터셋에는 없는 것
for i in dong :
    if i not in d :
        print(i)

상일동

In [12]:
dict = {dong[i]:num[i] for i in range(len(num))}
dict

{'청운효자동': 13.0,
 '사직동': 30.0,
 '삼청동': 7.0,
 '부암동': 10.0,
 '평창동': 15.0,
 '무악동': 4.0,
 '교남동': 16.0,
 '가회동': 7.0,
 '종로1.2.3.4가동': 107.0,
 '종로5.6가동': 24.0,
 '이화동': 20.0,
 '혜화동': 32.0,
 '창신1동': 10.0,
 '창신2동': 4.0,
 '창신3동': 3.0,
 '숭인1동': 8.0,
 '숭인2동': 24.0,
 '소공동': 50.0,
 '회현동': 58.0,
 '명동': 84.0,
 '필동': 29.0,
 '장충동': 14.0,
 '광희동': 43.0,
 '을지로동': 34.0,
 '신당동': 31.0,
 '다산동': 16.0,
 '약수동': 12.0,
 '청구동': 5.0,
 '신당5동': 8.0,
 '동화동': 9.0,
 '황학동': 13.0,
 '중림동': 14.0,
 '후암동': 19.0,
 '용산2가동': 20.0,
 '남영동': 31.0,
 '청파동': 27.0,
 '원효로1동': 20.0,
 '원효로2동': 14.0,
 '효창동': 9.0,
 '용문동': 9.0,
 '한강로동': 49.0,
 '이촌1동': 13.0,
 '이촌2동': 7.0,
 '이태원1동': 25.0,
 '이태원2동': 13.0,
 '한남동': 26.0,
 '서빙고동': 10.0,
 '보광동': 10.0,
 '왕십리2동': 10.0,
 '왕십리도선동': 25.0,
 '마장동': 19.0,
 '사근동': 34.0,
 '행당1동': 21.0,
 '행당2동': 8.0,
 '응봉동': 5.0,
 '금호1가동': 8.0,
 '금호2.3가동': 17.0,
 '금호4가동': 7.0,
 '옥수동': 14.0,
 '성수1가1동': 22.0,
 '성수1가2동': 30.0,
 '성수2가1동': 23.0,
 '성수2가3동': 60.0,
 '송정동': 9.0,
 '용답동': 14.0,
 '화양동': 61.0,
 '군자동': 30.0,
 '중곡1동': 15.0,
 '중곡2동': 27.0,
 '중곡3동': 17.0,
 '중곡4동': 21.0,
 '능동': 17.0,
 '광장동': 21.0,
 '자양1동': 21.0,
 '자양2동': 22.0,
 '자양3동': 25.0,
 '자양4동': 29.0,
 '구의1동': 28.0,
 '구의2동': 19.0,
 '구의3동': 32.0,
 '용신동': 49.0,
 '제기동': 30.0,
 '전농1동': 29.0,
 '전농2동': 17.0,
 '답십리1동': 31.0,
 '답십리2동': 17.0,
 '장안1동': 57.0,
 '장안2동': 37.0,
 '청량리동': 17.0,
 '회기동': 21.0,
 '휘경1동': 16.0,
 '휘경2동': 17.0,
 '이문1동': 30.0,
 '이문2동': 12.0,
 '면목2동': 22.0,
 '면목4동': 15.0,
 '면목5동': 8.0,
 '면목본동': 29.0,
 '면목7동': 18.0,
 '면목3.8동': 21.0,
 '상봉1동': 18.0,
 '상봉2동': 33.0,
 '중화1동': 19.0,
 '중화2동': 20.0,
 '묵1동': 22.0,
 '묵2동': 17.0,
 '망우본동': 33.0,
 '망우3동': 12.0,
 '신내1동': 22.0,
 '신내2동': 10.0,
 '성북동': 16.0,
 '삼선동': 31.0,
 '동선동': 36.0,
 '돈암1동': 8.0,
 '돈암2동': 5.0,
 '안암동': 39.0,
 '보문동': 16.0,
 '정릉1동': 16.0,
 '정릉2동': 20.0,
 '정릉3동': 14.0,
 '정릉4동': 17.0,
 '길음1동': 10.0,
 '길음2동': 8.0,
 '종암동': 29.0,
 '월곡1동': 14.0,
 '월곡2동': 25.0,
 '장위1동': 15.0,
 '장위2동': 9.0,
 '장위3동': 9.0,
 '석관동': 24.0,
 '삼양동': 14.0,
 '미아동': 30.0,
 '송중동': 28.0,
 '송천동': 22.0,
 '삼각산동': 9.0,
 '번1동': 29.0,
 '번2동': 11.0,
 '번3동': 11.0,
 '수유1동': 22.0,
 '수유2동': 19.0,
 '수유3동': 36.0,
 '우이동': 18.0,
 '인수동': 27.0,
 '창1동': 15.0,
 '창2동': 19.0,
 '창3동': 14.0,
 '창4동': 21.0,
 '창5동': 21.0,
 '도봉1동': 23.0,
 '도봉2동': 15.0,
 '쌍문1동': 20.0,
 '쌍문2동': 14.0,
 '쌍문3동': 17.0,
 '쌍문4동': 12.0,
 '방학1동': 30.0,
 '방학2동': 18.0,
 '방학3동': 12.0,
 '월계1동': 33.0,
 '월계2동': 18.0,
 '월계3동': 10.0,
 '공릉1동': 43.0,
 '공릉2동': 38.0,
 '하계1동': 22.0,
 '하계2동': 6.0,
 '중계본동': 17.0,
 '중계1동': 16.0,
 '중계4동': 13.0,
 '중계2.3동': 13.0,
 '상계1동': 27.0,
 '상계2동': 31.0,
 '상계3.4동': 21.0,
 '상계5동': 18.0,
 '상계6.7동': 28.0,
 '상계8동': 5.0,
 '상계9동': 10.0,
 '상계10동': 6.0,
 '녹번동': 32.0,
 '불광1동': 16.0,
 '불광2동': 30.0,
 '갈현1동': 19.0,
 '갈현2동': 31.0,
 '구산동': 22.0,
 '대조동': 33.0,
 '응암1동': 26.0,
 '응암2동': 5.0,
 '응암3동': 34.0,
 '역촌동': 42.0,
 '신사1동': 18.0,
 '신사2동': 12.0,
 '증산동': 15.0,
 '수색동': 4.0,
 '진관동': 38.0,
 '천연동': 10.0,
 '북아현동': 8.0,
 '충현동': 32.0,
 '신촌동': 81.0,
 '연희동': 44.0,
 '홍제1동': 21.0,
 '홍제3동': 13.0,
 '홍제2동': 6.0,
 '홍은1동': 15.0,
 '홍은2동': 29.0,
 '남가좌1동': 9.0,
 '남가좌2동': 26.0,
 '북가좌1동': 11.0,
 '북가좌2동': 32.0,
 '아현동': 26.0,
 '공덕동': 29.0,
 '도화동': 26.0,
 '용강동': 29.0,
 '대흥동': 35.0,
 '염리동': 10.0,
 '신수동': 16.0,
 '서강동': 33.0,
 '서교동': 120.0,
 '합정동': 28.0,
 '망원1동': 27.0,
 '망원2동': 18.0,
 '연남동': 25.0,
 '성산1동': 28.0,
 '성산2동': 34.0,
 '상암동': 47.0,
 '목1동': 34.0,
 '목2동': 26.0,
 '목3동': 18.0,
 '목4동': 20.0,
 '목5동': 20.0,
 '신월1동': 14.0,
 '신월2동': 12.0,
 '신월3동': 12.0,
 '신월4동': 17.0,
 '신월5동': 20.0,
 '신월6동': 9.0,
 '신월7동': 15.0,
 '신정1동': 12.0,
 '신정2동': 10.0,
 '신정3동': 27.0,
 '신정4동': 39.0,
 '신정6동': 13.0,
 '신정7동': 9.0,
 '염창동': 32.0,
 '등촌1동': 40.0,
 '등촌2동': 11.0,
 '등촌3동': 26.0,
 '화곡1동': 58.0,
 '화곡2동': 12.0,
 '화곡3동': 16.0,
 '화곡4동': 16.0,
 '화곡본동': 28.0,
 '화곡6동': 33.0,
 '화곡8동': 16.0,
 '가양1동': 88.0,
 '가양2동': 7.0,
 '가양3동': 8.0,
 '발산1동': 41.0,
 '우장산동': 24.0,
 '공항동': 49.0,
 '방화1동': 33.0,
 '방화2동': 29.0,
 '방화3동': 21.0,
 '신도림동': 32.0,
 '구로1동': 12.0,
 '구로2동': 30.0,
 '구로3동': 68.0,
 '구로4동': 20.0,
 '구로5동': 33.0,
 '가리봉동': 14.0,
 '고척1동': 16.0,
 '고척2동': 29.0,
 '개봉1동': 22.0,
 '개봉2동': 16.0,
 '개봉3동': 9.0,
 '오류1동': 25.0,
 '오류2동': 34.0,
 '수궁동': 23.0,
 '가산동': 128.0,
 '독산1동': 47.0,
 '독산2동': 17.0,
 '독산3동': 22.0,
 '독산4동': 13.0,
 '시흥1동': 39.0,
 '시흥2동': 4.0,
 '시흥3동': 10.0,
 '시흥4동': 12.0,
 '시흥5동': 18.0,
 '영등포본동': 21.0,
 '영등포동': 66.0,
 '여의동': 111.0,
 '당산1동': 38.0,
 '당산2동': 44.0,
 '도림동': 12.0,
 '문래동': 44.0,
 '양평1동': 24.0,
 '양평2동': 37.0,
 '신길1동': 17.0,
 '신길3동': 11.0,
 '신길4동': 7.0,
 '신길5동': 9.0,
 '신길6동': 16.0,
 '신길7동': 19.0,
 '대림1동': 15.0,
 '대림2동': 21.0,
 '대림3동': 28.0,
 '노량진1동': 42.0,
 '노량진2동': 19.0,
 '상도1동': 47.0,
 '상도2동': 19.0,
 '상도3동': 14.0,
 '상도4동': 14.0,
 '흑석동': 27.0,
 '사당1동': 29.0,
 '사당2동': 28.0,
 '사당3동': 14.0,
 '사당4동': 8.0,
 '사당5동': 11.0,
 '대방동': 35.0,
 '신대방1동': 12.0,
 '신대방2동': 30.0,
 '보라매동': 19.0,
 '청림동': 7.0,
 '성현동': 10.0,
 '행운동': 30.0,
 '낙성대동': 28.0,
 '청룡동': 45.0,
 '은천동': 24.0,
 '중앙동': 20.0,
 '인헌동': 20.0,
 '남현동': 18.0,
 '서원동': 29.0,
 '신원동': 10.0,
 '서림동': 23.0,
 '신사동관': 27.0,
 '신림동': 36.0,
 '난향동': 3.0,
 '조원동': 23.0,
 '대학동': 36.0,
 '삼성동': 10.0,
 '미성동': 22.0,
 '난곡동': 22.0,
 '서초1동': 37.0,
 '서초2동': 46.0,
 '서초3동': 77.0,
 '서초4동': 35.0,
 '잠원동': 25.0,
 '반포본동': 7.0,
 '반포1동': 25.0,
 '반포2동': 7.0,
 '반포3동': 11.0,
 '반포4동': 43.0,
 '방배본동': 20.0,
 '방배1동': 20.0,
 '방배2동': 25.0,
 '방배3동': 17.0,
 '방배4동': 22.0,
 '양재1동': 46.0,
 '양재2동': 45.0,
 '내곡동': 11.0,
 '신사동강': 42.0,
 '논현1동': 76.0,
 '논현2동': 69.0,
 '압구정동': 57.0,
 '청담동': 55.0,
 '삼성1동': 57.0,
 '삼성2동': 51.0,
 '대치1동': 21.0,
 '대치2동': 49.0,
 '대치4동': 59.0,
 '역삼1동': 189.0,
 '역삼2동': 54.0,
 '도곡1동': 27.0,
 '도곡2동': 26.0,
 '개포1동': 2.0,
 '개포2동': 9.0,
 '개포4동': 29.0,
 '세곡동': 22.0,
 '일원본동': 13.0,
 '일원1동': 11.0,
 '일원2동': 8.0,
 '수서동': 19.0,
 '풍납1동': 8.0,
 '풍납2동': 21.0,
 '거여1동': 12.0,
 '거여2동': 11.0,
 '마천1동': 14.0,
 '마천2동': 11.0,
 '방이1동': 19.0,
 '방이2동': 39.0,
 '오륜동': 15.0,
 '오금동': 43.0,
 '송파1동': 27.0,
 '송파2동': 16.0,
 '석촌동': 45.0,
 '삼전동': 34.0,
 '가락본동': 40.0,
 '가락1동': 10.0,
 '가락2동': 20.0,
 '문정1동': 16.0,
 '문정2동': 63.0,
 '장지동': 19.0,
 '위례동': 17.0,
 '잠실본동': 54.0,
 '잠실2동': 19.0,
 '잠실3동': 19.0,
 '잠실4동': 6.0,
 '잠실6동': 26.0,
 '잠실7동': 1.0,
 '강일동': 30.0,
 '상일동': 18.0,
 '명일1동': 17.0,
 '명일2동': 17.0,
 '고덕1동': 7.0,
 '고덕2동': 9.0,
 '암사1동': 32.0,
 '암사2동': 11.0,
 '암사3동': 7.0,
 '천호1동': 21.0,
 '천호2동': 50.0,
 '천호3동': 25.0,
 '성내1동': 21.0,
 '성내2동': 30.0,
 '성내3동': 33.0,
 '길동': 60.0,
 '둔촌1동': 4.0,
 '둔촌2동': 20.0}

In [18]:
temp = []
for i in d :
    for j in dong :
        if i == j :
            temp.append(dict[i])

    if i == '항동' :
        temp.append(8)
    if i == '상일1동' :
        temp.append(7)  
    if i == '상일2동' :
        temp.append(0) 

temp

[30.0,
 7.0,
 10.0,
 15.0,
 4.0,
 16.0,
 7.0,
 107.0,
 24.0,
 20.0,
 10.0,
 4.0,
 3.0,
 8.0,
 24.0,
 13.0,
 32.0,
 50.0,
 58.0,
 84.0,
 29.0,
 14.0,
 43.0,
 34.0,
 8.0,
 13.0,
 14.0,
 31.0,
 16.0,
 12.0,
 5.0,
 9.0,
 19.0,
 20.0,
 31.0,
 14.0,
 9.0,
 9.0,
 13.0,
 7.0,
 25.0,
 13.0,
 10.0,
 10.0,
 27.0,
 20.0,
 49.0,
 26.0,
 10.0,
 19.0,
 34.0,
 21.0,
 8.0,
 5.0,
 8.0,
 7.0,
 22.0,
 30.0,
 23.0,
 60.0,
 9.0,
 14.0,
 25.0,
 17.0,
 14.0,
 61.0,
 30.0,
 15.0,
 27.0,
 17.0,
 21.0,
 17.0,
 28.0,
 19.0,
 32.0,
 21.0,
 21.0,
 22.0,
 25.0,
 29.0,
 21.0,
 16.0,
 17.0,
 17.0,
 49.0,
 30.0,
 29.0,
 17.0,
 17.0,
 57.0,
 37.0,
 30.0,
 12.0,
 31.0,
 22.0,
 15.0,
 8.0,
 18.0,
 18.0,
 33.0,
 19.0,
 20.0,
 22.0,
 17.0,
 12.0,
 22.0,
 10.0,
 29.0,
 21.0,
 33.0,
 8.0,
 5.0,
 39.0,
 16.0,
 16.0,
 20.0,
 14.0,
 17.0,
 10.0,
 8.0,
 14.0,
 25.0,
 15.0,
 9.0,
 9.0,
 16.0,
 31.0,
 36.0,
 29.0,
 24.0,
 29.0,
 11.0,
 11.0,
 22.0,
 19.0,
 36.0,
 14.0,
 30.0,
 28.0,
 22.0,
 9.0,
 18.0,
 27.0,
 20.0,
 14.0,
 17.0,
 12.0,
 30.0,
 18.0,
 12.0,
 15.0,
 19.0,
 14.0,
 21.0,
 21.0,
 23.0,
 15.0,
 33.0,
 18.0,
 10.0,
 38.0,
 22.0,
 6.0,
 17.0,
 16.0,
 13.0,
 27.0,
 31.0,
 18.0,
 5.0,
 10.0,
 6.0,
 21.0,
 28.0,
 13.0,
 43.0,
 32.0,
 16.0,
 19.0,
 31.0,
 22.0,
 33.0,
 26.0,
 5.0,
 18.0,
 12.0,
 15.0,
 4.0,
 38.0,
 30.0,
 34.0,
 42.0,
 10.0,
 21.0,
 13.0,
 6.0,
 15.0,
 29.0,
 9.0,
 26.0,
 11.0,
 32.0,
 32.0,
 8.0,
 81.0,
 44.0,
 29.0,
 35.0,
 10.0,
 16.0,
 120.0,
 28.0,
 27.0,
 18.0,
 25.0,
 28.0,
 34.0,
 47.0,
 26.0,
 33.0,
 29.0,
 26.0,
 34.0,
 26.0,
 18.0,
 20.0,
 14.0,
 12.0,
 12.0,
 17.0,
 20.0,
 9.0,
 15.0,
 12.0,
 10.0,
 27.0,
 13.0,
 9.0,
 20.0,
 39.0,
 32.0,
 40.0,
 11.0,
 26.0,
 28.0,
 12.0,
 16.0,
 16.0,
 33.0,
 16.0,
 88.0,
 7.0,
 8.0,
 41.0,
 49.0,
 33.0,
 29.0,
 21.0,
 58.0,
 24.0,
 32.0,
 12.0,
 68.0,
 20.0,
 33.0,
 16.0,
 29.0,
 16.0,
 9.0,
 25.0,
 23.0,
 14.0,
 30.0,
 22.0,
 34.0,
 8,
 128.0,
 47.0,
 17.0,
 22.0,
 13.0,
 39.0,
 4.0,
 10.0,
 12.0,
 18.0,
 111.0,
 38.0,
 44.0,
 24.0,
 37.0,
 17.0,
 11.0,
 7.0,
 9.0,
 16.0,
 19.0,
 15.0,
 21.0,
 28.0,
 21.0,
 66.0,
 12.0,
 44.0,
 19.0,
 47.0,
 19.0,
 14.0,
 14.0,
 29.0,
 14.0,
 8.0,
 11.0,
 35.0,
 12.0,
 30.0,
 27.0,
 42.0,
 28.0,
 19.0,
 7.0,
 30.0,
 28.0,
 20.0,
 20.0,
 18.0,
 29.0,
 10.0,
 23.0,
 27.0,
 36.0,
 3.0,
 23.0,
 36.0,
 24.0,
 10.0,
 45.0,
 22.0,
 10.0,
 22.0,
 37.0,
 46.0,
 77.0,
 35.0,
 25.0,
 7.0,
 25.0,
 7.0,
 11.0,
 43.0,
 20.0,
 20.0,
 25.0,
 17.0,
 22.0,
 46.0,
 45.0,
 11.0,
 42.0,
 76.0,
 69.0,
 57.0,
 51.0,
 21.0,
 59.0,
 189.0,
 54.0,
 27.0,
 26.0,
 2.0,
 29.0,
 13.0,
 11.0,
 8.0,
 19.0,
 22.0,
 57.0,
 55.0,
 49.0,
 9.0,
 8.0,
 21.0,
 12.0,
 11.0,
 14.0,
 11.0,
 19.0,
 39.0,
 15.0,
 43.0,
 27.0,
 16.0,
 45.0,
 34.0,
 40.0,
 10.0,
 20.0,
 16.0,
 63.0,
 54.0,
 6.0,
 26.0,
 1.0,
 19.0,
 19.0,
 19.0,
 17.0,
 17.0,
 17.0,
 7.0,
 9.0,
 11.0,
 7.0,
 21.0,
 25.0,
 21.0,
 30.0,
 33.0,
 4.0,
 20.0,
 32.0,
 50.0,
 60.0,
 30.0,
 7,
 0]

In [19]:
df['편의점 수'] = temp

In [20]:
df

       구     동  편의점 수
0    종로구   사직동   30.0
1    종로구   삼청동    7.0
2    종로구   부암동   10.0
3    종로구   평창동   15.0
4    종로구   무악동    4.0
..   ...   ...    ...
421  강동구  천호2동   50.0
422  강동구    길동   60.0
423  강동구   강일동   30.0
424  강동구  상일1동    7.0
425  강동구  상일2동    0.0

[426 rows x 3 columns]

In [21]:
df.to_csv('행정동별 편의점 수.csv')

In [22]:
for i in d :
    print(i)

사직동
삼청동
부암동
평창동
무악동
교남동
가회동
종로1.2.3.4가동
종로5.6가동
이화동
창신1동
창신2동
창신3동
숭인1동
숭인2동
청운효자동
혜화동
소공동
회현동
명동
필동
장충동
광희동
을지로동
신당5동
황학동
중림동
신당동
다산동
약수동
청구동
동화동
후암동
용산2가동
남영동
원효로2동
효창동
용문동
이촌1동
이촌2동
이태원1동
이태원2동
서빙고동
보광동
청파동
원효로1동
한강로동
한남동
왕십리2동
마장동
사근동
행당1동
행당2동
응봉동
금호1가동
금호4가동
성수1가1동
성수1가2동
성수2가1동
성수2가3동
송정동
용답동
왕십리도선동
금호2.3가동
옥수동
화양동
군자동
중곡1동
중곡2동
중곡3동
중곡4동
능동
구의1동
구의2동
구의3동
광장동
자양1동
자양2동
자양3동
자양4동
회기동
휘경1동
휘경2동
청량리동
용신동
제기동
전농1동
전농2동
답십리2동
장안1동
장안2동
이문1동
이문2동
답십리1동
면목2동
면목4동
면목5동
면목7동
상봉1동
상봉2동
중화1동
중화2동
묵1동
묵2동
망우3동
신내1동
신내2동
면목본동
면목3.8동
망우본동
돈암1동
돈암2동
안암동
보문동
정릉1동
정릉2동
정릉3동
정릉4동
길음1동
길음2동
월곡1동
월곡2동
장위1동
장위2동
장위3동
성북동
삼선동
동선동
종암동
석관동
번1동
번2동
번3동
수유1동
수유2동
수유3동
삼양동
미아동
송중동
송천동
삼각산동
우이동
인수동
쌍문1동
쌍문2동
쌍문3동
쌍문4동
방학1동
방학2동
방학3동
창1동
창2동
창3동
창4동
창5동
도봉1동
도봉2동
월계1동
월계2동
월계3동
공릉2동
하계1동
하계2동
중계본동
중계1동
중계4동
상계1동
상계2동
상계5동
상계8동
상계9동
상계10동
상계3.4동
상계6.7동
중계2.3동
공릉1동
녹번동
불광1동
갈현1동
갈현2동
구산동
대조동
응암1동
응암2동
신사1동
신사2동
증산동
수색동
진관동
불광2동
응암3동
역촌동
천연동
홍제1동
홍제3동
홍제2동
홍은1동
홍은2동
남가좌1동
남가좌2동
북가좌1동
북가좌2동
충현동
북아현동
신촌동
연희동
용강동
대흥동
염리동
신수동
서교동
합정동
망원1동
망원2동
연남동
성산1동
성산2동
상암동
도화동
서강동
공덕동
아현동
목1동
목2동
목3동
목4동
신월1동
신월2동
신월3동
신월4동
신월5동
신월6동
신월7동
신정1동
신정2동
신정3동
신정6동
신정7동
목5동
신정4동
염창동
등촌1동
등촌2동
등촌3동
화곡본동
화곡2동
화곡3동
화곡4동
화곡6동
화곡8동
가양1동
가양2동
가양3동
발산1동
공항동
방화1동
방화2동
방화3동
화곡1동
우장산동
신도림동
구로1동
구로3동
구로4동
구로5동
고척1동
고척2동
개봉2동
개봉3동
오류1동
수궁동
가리봉동
구로2동
개봉1동
오류2동
항동
가산동
독산1동
독산2동
독산3동
독산4동
시흥1동
시흥2동
시흥3동
시흥4동
시흥5동
여의동
당산1동
당산2동
양평1동
양평2동
신길1동
신길3동
신길4동
신길5동
신길6동
신길7동
대림1동
대림2동
대림3동
영등포본동
영등포동
도림동
문래동
노량진2동
상도1동
상도2동
상도3동
상도4동
사당1동
사당3동
사당4동
사당5동
대방동
신대방1동
신대방2동
흑석동
노량진1동
사당2동
보라매동
청림동
행운동
낙성대동
중앙동
인헌동
남현동
서원동
신원동
서림동
신사동관
신림동
난향동
조원동
대학동
은천동
성현동
청룡동
난곡동
삼성동
미성동
서초1동
서초2동
서초3동
서초4동
잠원동
반포본동
반포1동
반포2동
반포3동
반포4동
방배본동
방배1동
방배2동
방배3동
방배4동
양재1동
양재2동
내곡동
신사동강
논현1동
논현2동
삼성1동
삼성2동
대치1동
대치4동
역삼1동
역삼2동
도곡1동
도곡2동
개포1동
개포4동
일원본동
일원1동
일원2동
수서동
세곡동
압구정동
청담동
대치2동
개포2동
풍납1동
풍납2동
거여1동
거여2동
마천1동
마천2동
방이1동
방이2동
오륜동
오금동
송파1동
송파2동
석촌동
삼전동
가락본동
가락1동
가락2동
문정1동
문정2동
잠실본동
잠실4동
잠실6동
잠실7동
잠실2동
잠실3동
장지동
위례동
명일1동
명일2동
고덕1동
고덕2동
암사2동
암사3동
천호1동
천호3동
성내1동
성내2동
성내3동
둔촌1동
둔촌2동
암사1동
천호2동
길동
강일동
상일1동
상일2동

In [23]:
for i in dong :
    print(i)

청운효자동
사직동
삼청동
부암동
평창동
무악동
교남동
가회동
종로1.2.3.4가동
종로5.6가동
이화동
혜화동
창신1동
창신2동
창신3동
숭인1동
숭인2동
소공동
회현동
명동
필동
장충동
광희동
을지로동
신당동
다산동
약수동
청구동
신당5동
동화동
황학동
중림동
후암동
용산2가동
남영동
청파동
원효로1동
원효로2동
효창동
용문동
한강로동
이촌1동
이촌2동
이태원1동
이태원2동
한남동
서빙고동
보광동
왕십리2동
왕십리도선동
마장동
사근동
행당1동
행당2동
응봉동
금호1가동
금호2.3가동
금호4가동
옥수동
성수1가1동
성수1가2동
성수2가1동
성수2가3동
송정동
용답동
화양동
군자동
중곡1동
중곡2동
중곡3동
중곡4동
능동
광장동
자양1동
자양2동
자양3동
자양4동
구의1동
구의2동
구의3동
용신동
제기동
전농1동
전농2동
답십리1동
답십리2동
장안1동
장안2동
청량리동
회기동
휘경1동
휘경2동
이문1동
이문2동
면목2동
면목4동
면목5동
면목본동
면목7동
면목3.8동
상봉1동
상봉2동
중화1동
중화2동
묵1동
묵2동
망우본동
망우3동
신내1동
신내2동
성북동
삼선동
동선동
돈암1동
돈암2동
안암동
보문동
정릉1동
정릉2동
정릉3동
정릉4동
길음1동
길음2동
종암동
월곡1동
월곡2동
장위1동
장위2동
장위3동
석관동
삼양동
미아동
송중동
송천동
삼각산동
번1동
번2동
번3동
수유1동
수유2동
수유3동
우이동
인수동
창1동
창2동
창3동
창4동
창5동
도봉1동
도봉2동
쌍문1동
쌍문2동
쌍문3동
쌍문4동
방학1동
방학2동
방학3동
월계1동
월계2동
월계3동
공릉1동
공릉2동
하계1동
하계2동
중계본동
중계1동
중계4동
중계2.3동
상계1동
상계2동
상계3.4동
상계5동
상계6.7동
상계8동
상계9동
상계10동
녹번동
불광1동
불광2동
갈현1동
갈현2동
구산동
대조동
응암1동
응암2동
응암3동
역촌동
신사1동
신사2동
증산동
수색동
진관동
천연동
북아현동
충현동
신촌동
연희동
홍제1동
홍제3동
홍제2동
홍은1동
홍은2동
남가좌1동
남가좌2동
북가좌1동
북가좌2동
아현동
공덕동
도화동
용강동
대흥동
염리동
신수동
서강동
서교동
합정동
망원1동
망원2동
연남동
성산1동
성산2동
상암동
목1동
목2동
목3동
목4동
목5동
신월1동
신월2동
신월3동
신월4동
신월5동
신월6동
신월7동
신정1동
신정2동
신정3동
신정4동
신정6동
신정7동
염창동
등촌1동
등촌2동
등촌3동
화곡1동
화곡2동
화곡3동
화곡4동
화곡본동
화곡6동
화곡8동
가양1동
가양2동
가양3동
발산1동
우장산동
공항동
방화1동
방화2동
방화3동
신도림동
구로1동
구로2동
구로3동
구로4동
구로5동
가리봉동
고척1동
고척2동
개봉1동
개봉2동
개봉3동
오류1동
오류2동
수궁동
가산동
독산1동
독산2동
독산3동
독산4동
시흥1동
시흥2동
시흥3동
시흥4동
시흥5동
영등포본동
영등포동
여의동
당산1동
당산2동
도림동
문래동
양평1동
양평2동
신길1동
신길3동
신길4동
신길5동
신길6동
신길7동
대림1동
대림2동
대림3동
노량진1동
노량진2동
상도1동
상도2동
상도3동
상도4동
흑석동
사당1동
사당2동
사당3동
사당4동
사당5동
대방동
신대방1동
신대방2동
보라매동
청림동
성현동
행운동
낙성대동
청룡동
은천동
중앙동
인헌동
남현동
서원동
신원동
서림동
신사동관
신림동
난향동
조원동
대학동
삼성동
미성동
난곡동
서초1동
서초2동
서초3동
서초4동
잠원동
반포본동
반포1동
반포2동
반포3동
반포4동
방배본동
방배1동
방배2동
방배3동
방배4동
양재1동
양재2동
내곡동
신사동강
논현1동
논현2동
압구정동
청담동
삼성1동
삼성2동
대치1동
대치2동
대치4동
역삼1동
역삼2동
도곡1동
도곡2동
개포1동
개포2동
개포4동
세곡동
일원본동
일원1동
일원2동
수서동
풍납1동
풍납2동
거여1동
거여2동
마천1동
마천2동
방이1동
방이2동
오륜동
오금동
송파1동
송파2동
석촌동
삼전동
가락본동
가락1동
가락2동
문정1동
문정2동
장지동
위례동
잠실본동
잠실2동
잠실3동
잠실4동
잠실6동
잠실7동
강일동
상일동
명일1동
명일2동
고덕1동
고덕2동
암사1동
암사2동
암사3동
천호1동
천호2동
천호3동
성내1동
성내2동
성내3동
길동
둔촌1동
둔촌2동

In [24]:
print(len(d))
print(len(dong))

426
424